### ISSUE TITLE
Unexpected token: account moved

### ISSUE THREAD

**Issue by AeliusSaionji** [cucmberium/Flantter#137]
I've been getting these errors when the app starts and when I do a refresh. Seems to only affect Mastodon, not twitter.

![screenshot 5](https://user-images.githubusercontent.com/4342746/44674848-c6628c00-a9fc-11e8-9b10-c3f585153012.png)

**Comment by YDKK** [comment]
Will be fixed by this PR: https://github.com/cucmberium/TootNet/pull/4

**Comment by AeliusSaionji** [comment]
Fixed! Thank you.
